#ifndef RAPL_DEFINE_H
#define RAPL_DEFINE_H

#define MSR_RAPL_POWER_UNIT		0x606

/*
 * Platform specific RAPL Domains.
 * Note that PP1 RAPL Domain is supported on 062A only
 * And DRAM RAPL Domain is supported on 062D only
 */
/* Package RAPL Domain */
#define MSR_PKG_RAPL_POWER_LIMIT 0x610
#define MSR_PKG_ENERGY_STATUS	 0x611
#define MSR_PKG_PERF_STATUS		 0x613
#define MSR_PKG_POWER_INFO		 0x614

/* PP0 RAPL Domain */
#define MSR_PP0_POWER_LIMIT		0x638
#define MSR_PP0_ENERGY_STATUS	0x639
#define MSR_PP0_POLICY			0x63A
#define MSR_PP0_PERF_STATUS		0x63B

/* PP1 RAPL Domain, may reflect to uncore devices */
#define MSR_PP1_POWER_LIMIT		0x640
#define MSR_PP1_ENERGY_STATUS	0x641
#define MSR_PP1_POLICY			0x642

/* DRAM RAPL Domain */
#define MSR_DRAM_POWER_LIMIT	0x618
#define MSR_DRAM_ENERGY_STATUS	0x619
#define MSR_DRAM_PERF_STATUS	0x61B
#define MSR_DRAM_POWER_INFO		0x61C

/* PSYS RAPL Domain */
#define MSR_PLATFORM_ENERGY_STATUS	0x64d

/* RAPL UNIT BITMASK */
#define POWER_UNIT_OFFSET	0
#define POWER_UNIT_MASK		0x0F

#define ENERGY_UNIT_OFFSET	0x08
#define ENERGY_UNIT_MASK	0x1F00

#define TIME_UNIT_OFFSET	0x10
#define TIME_UNIT_MASK		0xF000

#define CPU_SANDYBRIDGE		 42
#define CPU_SANDYBRIDGE_EP	 45
#define CPU_IVYBRIDGE		 58
#define CPU_IVYBRIDGE_EP	 62
#define CPU_HASWELL		     60
#define CPU_HASWELL_ULT		 69
#define CPU_HASWELL_GT3E	 70
#define CPU_HASWELL_EP		 63
#define CPU_BROADWELL		 61
#define CPU_BROADWELL_GT3E	 71
#define CPU_BROADWELL_EP	 79
#define CPU_BROADWELL_DE	 86
#define CPU_SKYLAKE		     78
#define CPU_SKYLAKE_HS		 94
#define CPU_SKYLAKE_X		 85
#define CPU_KNIGHTS_LANDING	 87
#define CPU_KNIGHTS_MILL	 133
#define CPU_KABYLAKE_MOBILE	 142
#define CPU_KABYLAKE		 158
#define CPU_ATOM_SILVERMONT	 55
#define CPU_ATOM_AIRMONT	 76
#define CPU_ATOM_MERRIFIELD	 74
#define CPU_ATOM_MOOREFIELD	 90
#define CPU_ATOM_GOLDMONT	 92
#define CPU_ATOM_GEMINI_LAKE 122
#define CPU_ATOM_DENVERTON	 95

#define MAX_CPUS	1024
#define MAX_PACKAGES   4
//#define MAX_PACKAGES 1

#define NUM_RAPL_DOMAINS    5

#endif
